### ISSUE TITLE
cannot start server

### ISSUE THREAD

**Issue by kilianc** [obastemur/mediaserver#4]
```
/Volumes/WS/tmp/node_modules/mediaserver/index.js:123
        res.write("Media format couldn't found for " + pathmodule.basename(pat
                                                       ^
ReferenceError: pathmodule is not defined
    at Object.exports.pipe (/Volumes/WS/tmp/node_modules/mediaserver/index.js:123:56)
    at Server.<anonymous> (/Volumes/WS/tmp/airplay.js:39:6)
    at Server.emit (events.js:110:17)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:491:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
    at Socket.socketOnData (_http_server.js:343:22)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
```

**Comment by obastemur** [comment]
probably you were using it from npm it wasn't updated there. Please install it again. it should be fixed.
